from .tables import (
    Campaign,
    Customer,
    Dashboard,
    DashboardConfig,
    DataUpload,
    DataUploadRow,
    GenericJsonRecord,
    GoogleMapsLead,
    Organization,
    Segment,
    Tenant,
    TimestampMixin,
    User,
    WhatsAppAutoResponder,
    WhatsAppBulkJob,
    WhatsAppGroupTask,
    WhatsAppTemplate,
)
from .registry import create_tables

__all__ = (
    "Campaign",
    "Customer",
    "Dashboard",
    "DashboardConfig",
    "DataUpload",
    "DataUploadRow",
    "GenericJsonRecord",
    "GoogleMapsLead",
    "Organization",
    "Segment",
    "Tenant",
    "TimestampMixin",
    "User",
    "WhatsAppAutoResponder",
    "WhatsAppBulkJob",
    "WhatsAppGroupTask",
    "WhatsAppTemplate",
    "create_tables",
)
